[sensitivity]
x_sens = 0.7 # sensitivity in x direction
y_sens = 0.9 # sensitivity in y direction

[steps]
x_step = 1.3 # movement steps in x direction 
y_step = 1.5 # movement steps in y direction

[frames]
numf = 10 # for mouse movement
clickf = 10 # for click detection

[mode]
nod_shake_mode = 0 # the mode to start the application with (if 0, the application starts in normal mode, else it starts in 2-gestures mode; the mode can also be changed in the ui)

